### PR TITLE
fix pug support

### PR DESCRIPTION
**Pull request by shijimiYN**
related issue: https://github.com/express-vue/express-vue/issues/113

### CODE REVIEW

**Comment by danmademe** [comment]
There are indentation issues. Please run ‘npm test’ and fix issues. 

Push those fixes and I’ll merge. 

Thanks.

**Comment by shijimiYN** [comment]
OK, I'll do it.

**Comment by danmademe** [comment]
Thanks man. 

I’ll get this into the master and then push a new release.

**Comment by danmademe** [comment]
OK this will go out in 0.6.4 which should be up in 30~ minutes

**Comment by danmademe** [comment]
ill push a new update to express-vue on monday

**Comment by shijimiYN** [comment]
Thanks!
I'm surprised how well your repo is managed 😄

**Comment by danmademe** [comment]
Thanks.

**Pull request merged**
